In [3]:
#Broadcasting:
#First case:
import numpy as np
X = [ [1, 3, 2, 7], [8, 2, 3, 2] ]
X = np.array(X)
print(X.shape)

Y = [3]
Y = np.array(Y)
print(Y.shape)

Z = X*Y
print(Z)
print("The final dimension becomes: ", Z.shape)

(2, 4)
(1,)
[[ 3  9  6 21]
 [24  6  9  6]]
The final dimension becomes:  (2, 4)


In [4]:
#Broadcasting:
#2nd case:
import numpy as np
X = [ [1, 3, 2, 7], [8, 2, 3, 2] ]
X = np.array(X)
print(X.shape)

Y = [2,3,4,5]
Y = np.array(Y)
print(Y.shape)

Z = X*Y
print(Z)
print("The final dimension becomes: ", Z.shape)

(2, 4)
(4,)
[[ 2  9  8 35]
 [16  6 12 10]]
The final dimension becomes:  (2, 4)


In [7]:
#Third case:
X = [ [[7, 8], [6, 2], [7, 1]],
     [[3, 7], [12, 4], [6, 7]],
    [[3, 5], [4, 1], [9, 3]],
    [[5, 7], [12, 7], [9, 5]],
    [[7, 9], [1, 2], [6,4]]]

X = np.array(X)
print(X.shape)

Y = [ [[1, 4]],
     [[3, 5]],
    [[7, 9]],
    [[5, 7]],
    [[7, 7]]]
Y = np.array(Y)
print(Y.shape)

Z = X*Y
print(Z)
print("The final dimension becomes: ", Z.shape)

(5, 3, 2)
(5, 1, 2)
[[[ 7 32]
  [ 6  8]
  [ 7  4]]

 [[ 9 35]
  [36 20]
  [18 35]]

 [[21 45]
  [28  9]
  [63 27]]

 [[25 49]
  [60 49]
  [45 35]]

 [[49 63]
  [ 7 14]
  [42 28]]]
The final dimension becomes:  (5, 3, 2)


In [15]:
#Fourth case:
X = [ [[1, 3, 5, 7, 8], [8, 5, 6, 2, 1], [7, 1, 6, 4, 6]],
     [[3, 5, 7, 9, 2], [12, 4, 1, 2, 8], [6, 7, 8, 9, 1]],
    [[3, 5, 7, 9, 1], [12, 4, 1, 2, 4], [6, 7, 8, 9, 3]]]

X = np.array(X)
print(X.shape)

Y = [[1, 3, 5, 7, 8], [3, 5, 7, 9, 2], [3, 5, 7, 9, 1]]
Y = np.array(Y)
print(Y.shape)

Z = X*Y
print(Z)
print("The final dimension becomes: ", Z.shape)

(3, 3, 5)
(3, 5)
[[[ 1  9 25 49 64]
  [24 25 42 18  2]
  [21  5 42 36  6]]

 [[ 3 15 35 63 16]
  [36 20  7 18 16]
  [18 35 56 81  1]]

 [[ 3 15 35 63  8]
  [36 20  7 18  8]
  [18 35 56 81  3]]]
The final dimension becomes:  (3, 3, 5)


In [13]:
#Fifth case(A 3d(5x3x5) and a 2d(3x1) array broadcasting):
A = [ [[1, 3, 5, 7, 8], [8, 5, 6, 2, 1], [7, 1, 6, 4, 6]],
     [[3, 5, 7, 9, 2], [12, 4, 1, 2, 8], [6, 7, 8, 9, 1]],
    [[3, 5, 7, 9, 1], [12, 4, 1, 2, 4], [6, 7, 8, 9, 3]],
    [[3, 5, 7, 9, 4], [12, 4, 1, 2, 7], [6, 7, 8, 9, 5]]]
import numpy as np
A = np.array(A)
print("The shape of A: ",A.shape)

B = [[1], [2], [3]]
B = np.array(B)
B = B
print("The shape of B: ", B.shape)

C = A*B
print(C)
print("The final shape after broadcasting: ", C.shape)

The shape of A:  (4, 3, 5)
The shape of B:  (3, 1)
[[[ 1  3  5  7  8]
  [16 10 12  4  2]
  [21  3 18 12 18]]

 [[ 3  5  7  9  2]
  [24  8  2  4 16]
  [18 21 24 27  3]]

 [[ 3  5  7  9  1]
  [24  8  2  4  8]
  [18 21 24 27  9]]

 [[ 3  5  7  9  4]
  [24  8  2  4 14]
  [18 21 24 27 15]]]
The final shape after broadcasting:  (4, 3, 5)


In [49]:
#Failure cases(try 1: 2d and 2d array):
A = [ [1, 3, 5, 7], [8, 5, 6, 2], [7, 1, 6, 4], [3, 5, 7, 9], [12, 4, 1, 2] ]
import numpy as np
A = np.array(A)
print("The shape of A: ", A.shape)

B = [3, 4, 5, 6]
B = np.array(B)
print("The shape of B: ", B.shape)

C = A*B
print(C)
print("The final shape after broadcasting: ", C.shape)

The shape of A:  (5, 4)
The shape of B:  (4,)
[[ 3 12 25 42]
 [24 20 30 12]
 [21  4 30 24]
 [ 9 20 35 54]
 [36 16  5 12]]
The final shape after broadcasting:  (5, 4)


In [19]:
#Failure case:
X = [ [[1, 3, 5, 7, 8], [8, 5, 6, 2, 1], [7, 1, 6, 4, 6]],
     [[3, 5, 7, 9, 2], [12, 4, 1, 2, 8], [6, 7, 8, 9, 1]]]
X = np.array(X)
print(X.shape)

Y = [[1, 2, 3]]
Y = np.array(Y)
print(Y.shape)

Z = X*Y.T
print(Z)
print("The final dimension becomes: ", Z.shape)

(2, 3, 5)
(1, 3)
[[[ 1  3  5  7  8]
  [16 10 12  4  2]
  [21  3 18 12 18]]

 [[ 3  5  7  9  2]
  [24  8  2  4 16]
  [18 21 24 27  3]]]
The final dimension becomes:  (2, 3, 5)


In [57]:
#Second case(A 2d(5x4) and a 1d(4x1) array broadcasting):
A = [ [1], [8], [7], [3], [12] ]
import numpy as np
A = np.array(A)
print("The shape of A: ", A.shape)

B = [3, 4, 5, 6]
B = np.array(B)
B = B
print("The shape of B: ", B.shape)

C = A*B
print(C)
print("The final shape after broadcasting: ", C.shape)

The shape of A:  (5, 1)
The shape of B:  (4,)
[[ 3  4  5  6]
 [24 32 40 48]
 [21 28 35 42]
 [ 9 12 15 18]
 [36 48 60 72]]
The final shape after broadcasting:  (5, 4)
